# Generated by Django 4.2.2 on 2024-08-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_remove_order_exist_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exist',
            field=models.BooleanField(default=True, verbose_name='Существует?'),
        ),
    ]
