# Generated by Django 4.2.2 on 2024-09-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_order_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_and_tochka',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна производителя'),
        ),
    ]
